package jT3;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author allec
 */
public class Jframe extends javax.swing.JFrame {

    /**
     * Creates new form Jframe
     */
    public Jframe() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldNUM.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                jTextFieldNUM.setText("");
            }
        });
        jTextFieldLET.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                jTextFieldLET.setText("");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jExit = new javax.swing.JButton();
        jLabelLET = new javax.swing.JLabel();
        jLabelNUM = new javax.swing.JLabel();
        jButtonST2 = new javax.swing.JButton();
        jTextFieldLET = new javax.swing.JTextField();
        jButtonST1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldNUM = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jExit.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jExit.setMnemonic('P');
        jExit.setText("X");
        jExit.setToolTipText("Salir");
        jExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jExit.setContentAreaFilled(false);
        jExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jExit.setPreferredSize(new java.awt.Dimension(40, 40));
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        getContentPane().add(jExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 36, 36));

        jLabelLET.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabelLET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLET.setLabelFor(this);
        jLabelLET.setText("a");
        jLabelLET.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.orange));
        getContentPane().add(jLabelLET, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 70, 70));

        jLabelNUM.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jLabelNUM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNUM.setLabelFor(this);
        jLabelNUM.setText("0");
        jLabelNUM.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.red, java.awt.Color.orange));
        getContentPane().add(jLabelNUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 70, 70));

        jButtonST2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonST2.setText("START");
        jButtonST2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        jButtonST2.setContentAreaFilled(false);
        jButtonST2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonST2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonST2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonST2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jTextFieldLET.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLET.setText("Escriba una letra");
        getContentPane().add(jTextFieldLET, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 110, -1));

        jButtonST1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonST1.setText("START");
        jButtonST1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        jButtonST1.setContentAreaFilled(false);
        jButtonST1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonST1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonST1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 10, 10));

        jTextFieldNUM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNUM.setText("Escriba un numero");
        getContentPane().add(jTextFieldNUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jExitActionPerformed

    private void jButtonST1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonST1ActionPerformed
        String cont = jTextFieldNUM.getText();
        Hilo hilo1 = new Hilo(cont);
        hilo1.start();
        jTextFieldNUM.setText("Escriba un numero");
    }//GEN-LAST:event_jButtonST1ActionPerformed

    private void jButtonST2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonST2ActionPerformed
        String cont = jTextFieldLET.getText();
        Hilo hilo2 = new Hilo(cont);
        hilo2.start();
        jTextFieldLET.setText("Escriba una letra");
    }//GEN-LAST:event_jButtonST2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonST1;
    private javax.swing.JButton jButtonST2;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabelLET;
    private javax.swing.JLabel jLabelNUM;
    private javax.swing.JTextField jTextFieldLET;
    private javax.swing.JTextField jTextFieldNUM;
    // End of variables declaration//GEN-END:variables

    public class Hilo extends Thread {

        int c = 0;
        String contenido = "";

        public Hilo(String cnt) {
            this.contenido = cnt;
        }

        @Override
        public void run() {
            if (this.contenido.matches("[0-9]+")) {
                int c1 = Integer.parseInt(this.contenido);
                while (c1 < 100) {
                    c1 += 1;
                    jLabelNUM.setText(String.valueOf(c1));
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        System.out.println("Error");
                    }
                }
            } else {
                char l1 = this.contenido.charAt(0);
                while (l1 < 122) {
                    l1 += 1;
                    jLabelLET.setText(String.valueOf(l1));
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        System.out.println("Error");
                    }
                }
            }

            //int c1 = this.numeroUS;
//            int c2 = Integer.parseInt(jTextFieldNUM.getText());
        }
    }

}
